---
- name: Bootstrap devshell (virtual dev environment)
  hosts: dev
  remote_user: "{{ ansible_user }}"
  vars_files:
    - secrets.yaml
    - packages.yaml

  pre_tasks:
  - name: Update packages
    package:
      name: "*" 
      state: latest
    become: true

  - name: install repo packages
    package:
      name: "{{ dnf_packages }}"
      state: latest
    become: true

  - name: ensure podman is removed
    package:
      name: podman
      state: absent
    become: true

  - name: install asdf plugins
    shell: "asdf plugin-add {{ item }}"
    loop: "{{ asdf_plugins }}"
    register: command_output
    ignore_errors: true # needed because if plugin is already installed, asdf throws an error

  - name: update tldr pages
    shell: tldr --update

  roles:
    - role: geerlingguy.docker
      vars:
        # these options ensure you can use `docker compose`
        docker_install_compose_plugin: true
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present
        docker_users:
          - "{{ ansible_user }}"
        # note: must use `su - {{ ansible_user }}` or reboot to have access to docker without sudo
      become: true
